### ISSUE TITLE
PNG image is cropped into jpg

### ISSUE THREAD

**Issue by wongyoJung** [ggunti/react-native-amazing-cropper#23]
In IOS, png image is cropped into jpg..
I got image from local source
and it is well loaded into cropper and the cropping is done perfectly,
but the cropped image is converted into jpg.

**Comment by ggunti** [comment]
As you can see in the documentation, this library uses [`react-native-image-rotate`](https://github.com/dgladkov/react-native-image-rotate#readme) for image rotation and [`@react-native-community/image-editor`](https://github.com/react-native-community/react-native-image-editor) for image cropping. Probably one of these libraries causes the png -> jpg conversion on iOS, because in `react-native-amazing-cropper` I do not explicitly convert the returned image to jpg format.

**Comment by jordangrant** [comment]
Refer to https://github.com/react-native-community/react-native-image-editor/issues/37#issuecomment-694710262
